AWSTemplateFormatVersion: 2010-09-09
Description: |
  This cloud formation template is used to create the required resources for the
  glue job like s3 bucket creation, IAM roles addition and athena outputs in a s3 bucket location
  and creations of dynamo db table.

Parameters:
  S3BucketForGlue:
    Description: Please enter the name of this s3 bucket for getting the resources
      for the glue job
    Type: String
  IAMRoleNameForGlue:
    Description: Please enter the name of the IAM role used in AWS Glue job.
    Type: String

Resources:
  S3BucketCreationForGlueJob:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketForGlue

  GlueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleNameForGlue
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyName: AWSGlueServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                  - lakeformation:*
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeRouteTables
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcAttribute
                  - iam:ListRolePolicies
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - cloudwatch:PutMetricData
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::aws-glue-*/*
                  - arn:aws:s3:::*/*aws-glue-*/*
                  - !GetAtt S3BucketCreationForGlueJob.Arn
                  - !Join
                    - ''
                    - - !GetAtt S3BucketCreationForGlueJob.Arn
                      - /*
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::crawler-public*
                  - arn:aws:s3:::aws-glue-*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*:/aws-glue/*
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource:
                  - arn:aws:ec2:*:*:network-interface/*
                  - arn:aws:ec2:*:*:security-group/*
                  - arn:aws:ec2:*:*:instance/*
                Condition:
                  ForAllValues:StringEquals:
                    aws:TagKeys:
                      - aws-glue-service-resource

  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: AWSGlueAthenaWorkgroup
      Description: The workgroup for the johnny chivers aws glue course.
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation: !Sub s3://${S3BucketCreationForGlueJob}/athena

  StartupFundingDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: startup_funding
      BillingMode: PAYPERREQUEST  # On-demand capacity mode
      AttributeDefinitions:
        - AttributeName: Sr_No
          AttributeType: N
        - AttributeName: Startup_Name
          AttributeType: S
      KeySchema:
        - AttributeName: Sr_No
          KeyType: HASH   # Partition key
        - AttributeName: Startup_Name
          KeyType: RANGE  # Sort key

Outputs:
  S3Bucket:
    Description: The name of the s3 bucket created!
    Value: !Ref S3BucketCreationForGlueJob